global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets: ['weather-service-1:9001', 'weather-service-2:9002', 'weather-service-3:9003', 'disaster-service-1:9091', 'disaster-service-2:9092', 'disaster-service-3:9093', 'gateway:9080', 'service-discovery:9000']
      